name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  # This enables manual trigger from any branch
permissions:
  contents: read
  issues: write

jobs:
  pre-approval:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Print environment info
        run: |
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"

      - name: Check file structure
        run: |
          echo "Repository structure:"
          ls -la

      - name: Validate README
        run: |
          if [ -f "README.md" ]; then
            echo "README.md exists"
            cat README.md
          else
            echo "README.md does not exist"
            exit 1
          fi

  wait-for-approval:
    needs: pre-approval
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: "venkatesan-muniappan01"
          minimum-approvals: 1
          issue-title: "Approval required for workflow"
          issue-body: "Please approve this workflow to continue with post-approval tasks"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: "lgtm,approve,approved,approval,yes,ok"
          additional-denied-words: "deny,denied,no,reject,rejected"

  post-approval:
    needs: wait-for-approval
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Post-approval tasks
        run: |
          echo "These tasks will only run after manual approval"
          echo "Current date and time: $(date)"